### ISSUE TITLE
Pushing to a branch

### ISSUE THREAD

**Issue by adriaanbd** [adriaanbd/sample-landing-page#10]
Right now we are pushing to a branch directly, but instead we should submit a pull request, so it can be reviewed, approved and merged to the branch. I'm thinking that every feature should be developed in the `develop-bs` branch, and then submit a pull request to `bootstrap` branch. 

What we'd like to avoid is if the two of us are working on something at the same time, and we push to the branch, it's going to be a mess.

Any other suggestions?

**Comment by mcrd25** [comment]
Okay. 
Well we can do what you said and with addition of we both have our own branches that we integrate and merge with an integration branch (bs-develop). In this project may not be as necessary as us simply communicating effectively, but I do believe that doing this would help with how we use git and GitHub in future as coding partners. 

https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

Also here's a useful link on closing issues from command line using git: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by adriaanbd** [comment]
Really good articles, thank you. I believe I've read the first one before. So, in conclusion, if we use the right keywords in the commit message, the merge will close the issue automatically. It seems we would need to create a local branch for each issue / feature, then commit with appropriate message referencing the issue, push the branch, solicit a pull request, review, accept and delete the branch. Lets use develop-bs as the integration branch, which we'll merge to bootstrap branch later, when meeting certain criteria which we can define: like passing all html_requirements test (or another suggested by you), pass all reviews  of responsiveness in different screen sizes, etc.

Whatsha think?
